### PR TITLE
cleaned up hash logging

### PR DESCRIPTION
**Pull request by EIA485**

### CODE REVIEW

**Review by zkxs — APPROVED** [review]

**Comment by zkxs** [comment]
It looks like the build is angry about whitespace. Is that fixable, @EIA485 or do we need to bully the build system?

**Comment by EIA485** [comment]
hmm... not quite sure what its un happy about

**Comment by ljoonal** [comment]
Plz merge upstream & remove the extra editorconfig to see if lint will pass?

**Comment by EIA485** [comment]
> Plz merge upstream & remove the extra editorconfig to see if lint will pass?

figure we should add an editor config at some point to enforce our contributing guidelines in ide. should i move that to a separate pr?

**Comment by EIA485** [comment]
should i fix all the cs files that only have 2 space indentation caused by #59 ?

**Comment by EIA485** [comment]
realized an editor config was added in #59, moving changing that to match the current [CONTRIBUTING.md](https://github.com/neos-modding-group/NeosModLoader/blob/master/.github/CONTRIBUTING.md) to a separate pr

**Comment by EIA485** [comment]
squashed all the (now removed) .editorconfig shenanigans

**Review by zkxs — COMMENTED** [review]
I approve of the code, but due to the whitespace stuff I'm going to have to hold off on the overall approval until we get this sorted out.

**Comment by zkxs** [comment]
You can fix the merge conflict trivially with this:

```shell
git merge -X ours origin/master
dotnet format
```

**Review by ljoonal — APPROVED** [review]

**Review by ljoonal — APPROVED** [review]

**Pull request merged**
