### PR TITLE
Adds IgnoresAccessChecksToAttribute

### PR DESCRIPTION
**Pull request by Banane9**
Adding this to be able to properly mark mods using publicized assemblies while building, in case Neos ever moves off Mono or they change their behavior.

### CODE REVIEW

**Comment by Banane9** [comment]
Each mod would have to add the class definition by itself to use it. Since this has zero dependencies on anything and would save duplicate code / make it much easier to do properly for beginners, I think it makes sense to include to be proactive.

**Comment by zkxs** [comment]
I have no idea what's going on here. We can just declare an attribute in `System.Runtime.CompilerServices` and it somehow does something?

**Comment by Banane9** [comment]
> I have no idea what's going on here. We can just declare an attribute in `System.Runtime.CompilerServices` and it somehow does something?

Yea, for some reason that's what MS picked as the approach to allow assemblies to tell the runtime that it shouldn't check for access violations to specific assemblies.

https://stackoverflow.com/questions/69996924/ignoreaccesscheckstoattribute-does-not-grant-access-to-internal-types-in-referen

https://github.com/aelij/IgnoresAccessChecksToGenerator

**Comment by zkxs** [comment]
Wild... so what happens if two different assemblies provide `System.Runtime.CompilerServices.IgnoresAccessChecksToAttribute`? If NML adds this and some mod is already doing it, will things break?

**Comment by Banane9** [comment]
> If NML adds this and some mod is already doing it, will things break?

Well, so far I've not seen any mod that does it... but since IL contains assembly references for Types from other assemblies, it should be clear which one to use, otherwise any application where multiple assemblies have version of this attribute would fail as well.

**Review by zkxs — APPROVED** [review]

**Pull request merged**
