### PR TITLE
What if we used tabs, though?

### PR DESCRIPTION
**Pull request by zkxs**
Changes everything to tabs. Removes human-readable whitespace guidelines from CONTRIBUTING.md as they are superseded by editorconfig.

`dotnet format` doesn't run on csproj or sln files so I've formatted them manually.

**THE PRS WILL CONTINUE**  
**UNTIL MORALE IMPROVES**

### CODE REVIEW

**Review by EIA485 — APPROVED** [review]
looks good to me, 4 spaces are also fine if it really matters

**Review by ljoonal — APPROVED** [review]
To note since the previous PR was conserned about github rendering tabs as 8 spaces, that's configurable:

Github tab size settings

**Comment by EIA485** [comment]
if its configurable then this seems to be the best option, it can make everyone happy with their visual preference

**Comment by zkxs** [comment]
The people have spoken, and they are least bothered by tabs.

**Pull request merged**
