### PR TITLE
What if we used 4 spaces, though?

### PR DESCRIPTION
**Pull request by zkxs**
Changes everything (back) to four spaces. Removes human-readable whitespace guidelines from CONTRIBUTING.md as they are superseded by editorconfig.

`dotnet format` doesn't run on csproj or sln files so I've formatted them manually.

**THE PRS WILL CONTINUE**  
**UNTIL MORALE IMPROVES**

### CODE REVIEW

**Review by EIA485 — APPROVED** [review]
looks good to me. if tabs really cause issues then im happy to go with 4 spaces

**Review by ljoonal — COMMENTED** [review]
4 Spaces is a bit too much for me. Though if everyone else wants it I'm not going to stop the PR by requesting changes either.

**Comment by EIA485** [comment]
#65 seems to be the best option as it allows you to change the visual based on your preference within your editor

**Comment by zkxs** [comment]
#65 is the ultimate winner.

**Pull request closed without merging**
