### PR TITLE
Propper unified formatting

### PR DESCRIPTION
**Pull request by ljoonal**
Fixes CI hopefully.

I recommend reviewing with whitespace hidden.
image

### CODE REVIEW

**Comment by ljoonal** [comment]
I'm sure the CI will just magically fix this if we merge it, right @zkxs ? x'D

**Comment by EIA485** [comment]
Time to test in prod I guess ¯\_(ツ)_/¯

**Review by zkxs — APPROVED** [review]

**Comment by zkxs** [comment]
Hello merge conflicts my old friend~

**Comment by EIA485** [comment]
this seems to have messed up all of the indention. everything is only intended 2 spaces instead of 4

**Comment by zkxs** [comment]
Surely that was intentional? I doubt LJ overlooked a +2000 -2000 line diff.

**Comment by EIA485** [comment]
our [CONTRIBUTING.md](https://github.com/neos-modding-group/NeosModLoader/blob/master/.github/CONTRIBUTING.md) states cs files should have a 4 space indentation

**Comment by zkxs** [comment]
> our [CONTRIBUTING.md](https://github.com/neos-modding-group/NeosModLoader/blob/master/.github/CONTRIBUTING.md) states cs files should have a 4 space indentation

Well, seems like the move is to update CONTRIBUTING.md, then. #62 does that.

**Comment by ljoonal** [comment]
Apologies, I should've done more checking that the update matches the current styles instead of just quickly trying to fix the CI.

**Pull request merged**
