### PR TITLE
add sha 256 hash to loading log

### PR DESCRIPTION
**Pull request by EIA485**
this is helpful when acting as support for other users, sometimes mod authors forget to update there version numbers.
this will also be useful for the nml discord bot's neos log parsing feature

### CODE REVIEW

**Comment by ljoonal** [comment]
If we're adding this to mods should also add it to nml_libs

**Comment by ljoonal** [comment]
Also I feel like sha256 is way too long & overkill if we just want to use it to detect version, something more lightweight like crc32 for example would be a better fit.

**Comment by EIA485** [comment]
my reasoning for using sha256 is that its what we use on the manifest, i will add sha256 to nml_libs later today

**Comment by ljoonal** [comment]
Outside the scope of this PR then I guess, but I'm thinking about possibly makeking another PR to add support for https://github.com/xoofx/Blake3.NET if it's available after nml_libs assembly loads then if we want to support the hashes used in the manifest.

**Review by zkxs — APPROVED** [review]

**Comment by EIA485** [comment]
still changing stuff pls no merge

**Comment by zkxs** [comment]
> still changing stuff pls no merge

I think you can mark PRs as a draft to signal that they are not ready to beheld by mortal eyes yet

**Comment by EIA485** [comment]
ok, think this will be it for now, maybe in the future we can restructure some stuff

**Review by zkxs — APPROVED** [review]

**Pull request merged**
